package com.felipeska.banking.error;

public enum Error {
	ERROR_SAVE_CLIENT, ERROR_DELETE_CLIENT, CLIENT_ALREADY_REGISTERED, ERROR_EDIT_CLIENT, ERROR_SAVE_ACCOUNT, ACCOUNT_ALREADY_REGISTERED, NO_HAVE_MONEY,TRANSACTION_ERROR
}
